
@baseURL=http://localhost:8000

###
GET {{baseURL}}/api/users/


### 405 "detail": "Method \"POST\" not allowed."
# POST {{baseURL}}/users/6/
# Content-Type: application/json

# {
#     "username": "sdgf",
#     "email": "",
#     "groups": []
# }


### 可刪...
# DELETE {{baseURL}}/users/5/


### 查詢 [snippets]
GET {{baseURL}}/api/snippets/
Accept: text/html
# Accpet: text/html
# Accept: application/json


### 查詢 [snippets]
GET {{baseURL}}/api/snippets/


### 新增 snippets
POST {{baseURL}}/api/snippets/
Content-Type: application/json

{
    "code": "TEST11"
}


### 查詢 snippets
GET {{baseURL}}/api/snippets/2/


### 修改 snippets
PUT {{baseURL}}/api/snippets/2/
Content-Type: application/json

{
    "title": "new~",
    "code": "Hello"
}


### 刪除 snippets
DELETE {{baseURL}}/api/snippets/5/

